### ISSUE TITLE
[CY-6207] Project plugins

### ISSUE THREAD

**Issue by Trealent777** [codacy/codacy-aligncheck#13]
https://github.com/codacy/codacy-aligncheck/blob/master/project/plugins.sbt

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out!

Could you please provide more information? I don't quite understand your request. 😅 

Thank you!

Stefan

**Comment by stefanvacareanu7** [comment]
Closing issue due to lack of information.
